name: Hello World

on:
  push:
    branches:
      - main

jobs:
  hello_world_job:
    runs-on: ubuntu-20.04
    steps:
      - name: say_hello
        run: echo "Hello, World!"
      - name: get_directory
        run: ls -l
      - name: get_date
        run: date